// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Mongodb = require("mongodb");
var Process = require("process");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");
var Mongo$PublicbizApiV3 = require("./Mongo.bs.js");

var app = Express.express(/* () */0);

var mongoClient = Mongodb.MongoClient;

var mongoUrl = "mongodb://localhost:27017";

Express.App[/* get */4](app, "/", Express.Middleware[/* from */5]((function (param, param$1, res) {
            return Express.$$Response[/* sendString */2]("The PublicBizApi is working! ", Express.$$Response[/* status */9](/* Ok */0)(res));
          })));

Express.App[/* get */4](app, "/mongodb", Express.PromiseMiddleware[/* from */0]((function (param, param$1, res) {
            return Mongo$PublicbizApiV3.MongoDb[/* connectAsync */0](mongoClient, mongoUrl).then((function (c) {
                          var db = c.db("publicbiz");
                          var collection = db.collection("templates");
                          var d = { };
                          var cursor = collection.find(d);
                          cursor.toArray((function (param, docs) {
                                  console.log("Documents: ", docs);
                                  return /* () */0;
                                }));
                          return Promise.resolve(Express.$$Response[/* sendStatus */7](/* Ok */0)(res));
                        }));
          })));

var server = Express.App[/* listen */21](app, 9000, (function (e) {
        var exit = 0;
        var val;
        try {
          val = e;
          exit = 1;
        }
        catch (raw_exn){
          var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
          if (exn[0] === Js_exn.$$Error) {
            console.log(exn[1]);
            Process.exit(1);
            return /* () */0;
          } else {
            throw exn;
          }
        }
        if (exit === 1) {
          console.log("Server running at: http://localhost:9000");
          return /* () */0;
        }
        
      }), /* () */0);

exports.app = app;
exports.mongoClient = mongoClient;
exports.mongoUrl = mongoUrl;
exports.server = server;
/* app Not a pure module */
